### ISSUE TITLE
London Hardfork Updates

### ISSUE THREAD

**Issue by wolflo** [wolflo/evm-opcodes#10]
Update for the upcoming [London](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/london.md) hardfork. There is no mainnet block yet, but mid-July seems likely.

The relevant EIPs are probably EIP-3198 (`BASEFEE`), EIP-3529 (reduction in refunds), and EIP-3541 (reject new contracts with leading 0xEF byte).

**Comment by qbzzt** [comment]
BASEFEE added in #11

**Comment by wolflo** [comment]
Merged in #13.
