### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by Oni-giri** [wolflo/evm-opcodes#16]
Hi! I really love your guide, which is probably the best on the web about gas cost.

I saw a little typo [here](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion)

_"The memory cost function is linear up to 724 bytes of memory used, at which point additional memory costs substantially more."_  This refers to the formula: `gas_cost = (new_mem_size_words ^ 2 // 512) + (3 * new_mem_size_words) - Cmem(old_state)`.

I think you mean **724 32-bytes of memory**. Indeed, the line above states `new_mem_size_words = (new_mem_size + 31) // 32`: _number of (32-byte) words required for memory after the operation in question_

**Comment by wolflo** [comment]
Thanks for raising. I believe this is correct, though if it's confusing that may still be reason enough to change it.

The memory cost function, `floor(floor(mem_bytes / 32) ** 2 / 51) + 3 * floor(mem_bytes / 32)` is driven by the quadratic term (`new_mem_size_words ** 2`), which is divided by 512 and then floored. So, the quadratic term has no effect until it is `>= 512`.

This happens at `sqrt(512) == 22.6 words_of_mem == 724 bytes`
