### ISSUE TITLE
Berlin Hardfork Updates

### ISSUE THREAD

**Issue by wolflo** [wolflo/evm-opcodes#3]
Update for upcoming [Berlin](https://eips.ethereum.org/EIPS/eip-2070) hardfork, specifically adding `BEGINSUB`, `JUMPSUB`, and `RETURNSUB` opcodes from [EIP-2315](https://eips.ethereum.org/EIPS/eip-2315).

**Comment by wolflo** [comment]
The Berlin spec has been (mostly?) finalized. Fork block is still TBD.

https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/berlin.md

**Comment by frangio** [comment]
I'm looking forward to your breakdown of the dynamic costs of `SLOAD` and `SSTORE` from EIP-2929. :slightly_smiling_face: Lately I find myself consulting this EIP but I find it hard to navigate.

Love this resource you've put together. Thanks!

**Comment by wolflo** [comment]
@frangio yeah this is a tricky EIP. I need to take a bit more time on this one, but I'm hoping to update it soon

**Comment by wolflo** [comment]
https://gist.github.com/holiman/460f952716a74eeb9ab358bb1836d821

**Comment by wolflo** [comment]
https://twitter.com/TimBeiko/status/1362772348047294466

**Comment by wolflo** [comment]
@frangio If you have a chance to look over the [diff](https://github.com/wolflo/evm-opcodes/pull/8/files) for EIP-2929, any corrections you see are very appreciated.

**Comment by wolflo** [comment]
Merged in #8.
